#!/bin/bash

# Shared path defaults for the Qwen2.5 ReTool SFT/RL + OPD flow.
# Override these from the environment before launching any stage.

LOCAL_ENV_SH="${BASH_SOURCE[0]%/*}/local_recipe/local.env.sh"
if [ -f "${LOCAL_ENV_SH}" ]; then
   # Local-only overrides for private paths, ports, and machine-specific config.
   source "${LOCAL_ENV_SH}"
fi

SLIME_ROOT=${SLIME_ROOT:-/root/slime}
MEGATRON_PATH=${MEGATRON_PATH:-/root/Megatron-LM}

MODEL_ROOT=${MODEL_ROOT:-/root/Qwen}
DATA_ROOT=${DATA_ROOT:-/root}
OUTPUT_ROOT=${OUTPUT_ROOT:-/root/slime_outputs/retool_post_train_all}

QWEN2_5_7B_MODEL_NAME=${QWEN2_5_7B_MODEL_NAME:-Qwen2.5-7B-Instruct}
QWEN2_5_3B_MODEL_NAME=${QWEN2_5_3B_MODEL_NAME:-Qwen2.5-3B-Instruct}

QWEN2_5_7B_HF=${QWEN2_5_7B_HF:-${MODEL_ROOT}/${QWEN2_5_7B_MODEL_NAME}}
QWEN2_5_7B_TORCH_DIST=${QWEN2_5_7B_TORCH_DIST:-${MODEL_ROOT}/${QWEN2_5_7B_MODEL_NAME}_torch_dist}
QWEN2_5_7B_REF_LOAD=${QWEN2_5_7B_REF_LOAD:-${QWEN2_5_7B_TORCH_DIST}}
QWEN2_5_7B_SFT_SAVE=${QWEN2_5_7B_SFT_SAVE:-${OUTPUT_ROOT}/qwen2.5-7B-retool-sft}
QWEN2_5_7B_SFT_SAVE_HF=${QWEN2_5_7B_SFT_SAVE_HF:-}
QWEN2_5_7B_SFT_HF_EXPORT=${QWEN2_5_7B_SFT_HF_EXPORT:-${OUTPUT_ROOT}/qwen2.5-7B-retool-sft-hf}
QWEN2_5_7B_SFT_CLEAN_DIST=${QWEN2_5_7B_SFT_CLEAN_DIST:-${OUTPUT_ROOT}/qwen2.5-7B-retool-sft-clean-dist}
QWEN2_5_7B_RL_LOAD=${QWEN2_5_7B_RL_LOAD:-${QWEN2_5_7B_SFT_CLEAN_DIST}}
QWEN2_5_7B_RL_REF_LOAD=${QWEN2_5_7B_RL_REF_LOAD:-${QWEN2_5_7B_SFT_CLEAN_DIST}}
QWEN2_5_7B_RL_SAVE=${QWEN2_5_7B_RL_SAVE:-${OUTPUT_ROOT}/qwen2.5-7B-retool-rl}
QWEN2_5_7B_RL_SAVE_HF=${QWEN2_5_7B_RL_SAVE_HF:-${OUTPUT_ROOT}/qwen2.5-7B-retool-rl-hf}
QWEN2_5_7B_TEACHER_HF=${QWEN2_5_7B_TEACHER_HF:-${QWEN2_5_7B_RL_SAVE_HF}}
QWEN2_5_7B_ROTARY_BASE=${QWEN2_5_7B_ROTARY_BASE:-1000000}

QWEN2_5_3B_HF=${QWEN2_5_3B_HF:-${MODEL_ROOT}/${QWEN2_5_3B_MODEL_NAME}}
QWEN2_5_3B_TORCH_DIST=${QWEN2_5_3B_TORCH_DIST:-${MODEL_ROOT}/${QWEN2_5_3B_MODEL_NAME}_torch_dist}
QWEN2_5_3B_REF_LOAD=${QWEN2_5_3B_REF_LOAD:-${QWEN2_5_3B_TORCH_DIST}}
QWEN2_5_3B_SFT_SAVE=${QWEN2_5_3B_SFT_SAVE:-${OUTPUT_ROOT}/qwen2.5-3B-retool-sft}
QWEN2_5_3B_SFT_SAVE_HF=${QWEN2_5_3B_SFT_SAVE_HF:-}
QWEN2_5_3B_SFT_HF_EXPORT=${QWEN2_5_3B_SFT_HF_EXPORT:-${OUTPUT_ROOT}/qwen2.5-3B-retool-sft-hf}
QWEN2_5_3B_SFT_CLEAN_DIST=${QWEN2_5_3B_SFT_CLEAN_DIST:-${OUTPUT_ROOT}/qwen2.5-3B-retool-sft-clean-dist}
QWEN2_5_3B_OPD_LOAD=${QWEN2_5_3B_OPD_LOAD:-${QWEN2_5_3B_SFT_CLEAN_DIST}}
QWEN2_5_3B_OPD_REF_LOAD=${QWEN2_5_3B_OPD_REF_LOAD:-${QWEN2_5_3B_SFT_CLEAN_DIST}}
QWEN2_5_3B_OPD_SAVE=${QWEN2_5_3B_OPD_SAVE:-${OUTPUT_ROOT}/qwen2.5-3B-retool-opd}
QWEN2_5_3B_OPD_SAVE_HF=${QWEN2_5_3B_OPD_SAVE_HF:-${OUTPUT_ROOT}/qwen2.5-3B-retool-opd-hf}
QWEN2_5_3B_ROTARY_BASE=${QWEN2_5_3B_ROTARY_BASE:-1000000}

SFT_PROMPT_DATA=${SFT_PROMPT_DATA:-./data/retool/ReTool-SFT.parquet}
DAPO_MATH_DATA_DIR=${DAPO_MATH_DATA_DIR:-${DATA_ROOT}/dapo-math-17k}
AIME_2024_DATA_DIR=${AIME_2024_DATA_DIR:-${DATA_ROOT}/aime-2024}
AIME_2025_DATA_DIR=${AIME_2025_DATA_DIR:-${DATA_ROOT}/aime-2025}
AIME_DATA_DIR=${AIME_DATA_DIR:-${AIME_2024_DATA_DIR}}
RL_PROMPT_DATA=${RL_PROMPT_DATA:-${DAPO_MATH_DATA_DIR}/dapo-math-17k.jsonl}
OPD_PROMPT_DATA=${OPD_PROMPT_DATA:-${RL_PROMPT_DATA}}
EVAL_PROMPT_DATA_2024=${EVAL_PROMPT_DATA_2024:-${AIME_2024_DATA_DIR}/aime-2024.jsonl}
EVAL_PROMPT_DATA_2025=${EVAL_PROMPT_DATA_2025:-${AIME_2025_DATA_DIR}/aime-2025.jsonl}
EVAL_PROMPT_DATA=${EVAL_PROMPT_DATA:-${EVAL_PROMPT_DATA_2024}}
